[project]
name = "prama-server"
version = "0.1.0"
description = ""
authors = [
    {name = "migo",email = "1695587905@qq.com"}
]
readme = "README.md"
requires-python = ">=3.10, <3.13"
dependencies = [
    "prama (>=0.1.0a1,<0.2.0)",
    "typer (>=0.25.1,<0.26.0)",
    "fastapi (>=0.136.1,<0.137.0)",
    "uvicorn (>=0.46.0,<0.47.0)",
    "pydantic (>=2.13.3,<3.0.0)",
    "tqdm (>=4.67.3,<5.0.0)",
    "numpy (<2.3)",
    "pandas (<3)",
    "grpcio (>=1.80.0,<2.0.0)",
    "protobuf (>=7.34.1,<8.0.0)",
    "huggingface-hub (>=1.13.0,<2.0.0)",
    "soundfile (>=0.13.1,<0.14.0)",
    "librosa (>=0.11.0,<0.12.0)"
]

[tool.poetry]
packages = [{include = "prama_server", from = "src"}]

[[tool.poetry.source]]
name = "tuna"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
priority = "primary"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
