"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class AssessRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONFIG_FIELD_NUMBER: _builtins.int
    AUDIO_FIELD_NUMBER: _builtins.int
    audio: _builtins.bytes
    @_builtins.property
    def config(self) -> Global___QualityConfig: ...
    def __init__(
        self,
        *,
        config: Global___QualityConfig | None = ...,
        audio: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["config", b"config"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["audio", b"audio", "config", b"config"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AssessRequest: _TypeAlias = AssessRequest  # noqa: Y015

@_typing.final
class QualityConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _AudioEncoding:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _AudioEncodingEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[QualityConfig._AudioEncoding.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        AUDIO_ENCODING_UNSPECIFIED: QualityConfig._AudioEncoding.ValueType  # 0
        LINEAR16: QualityConfig._AudioEncoding.ValueType  # 1

    class AudioEncoding(_AudioEncoding, metaclass=_AudioEncodingEnumTypeWrapper): ...
    AUDIO_ENCODING_UNSPECIFIED: QualityConfig.AudioEncoding.ValueType  # 0
    LINEAR16: QualityConfig.AudioEncoding.ValueType  # 1

    ENCODING_FIELD_NUMBER: _builtins.int
    SAMPLE_RATE_HERTZ_FIELD_NUMBER: _builtins.int
    encoding: Global___QualityConfig.AudioEncoding.ValueType
    sample_rate_hertz: _builtins.int
    def __init__(
        self,
        *,
        encoding: Global___QualityConfig.AudioEncoding.ValueType = ...,
        sample_rate_hertz: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["encoding", b"encoding", "sample_rate_hertz", b"sample_rate_hertz"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___QualityConfig: _TypeAlias = QualityConfig  # noqa: Y015

@_typing.final
class AssessResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SCORE_FIELD_NUMBER: _builtins.int
    score: _builtins.float
    def __init__(
        self,
        *,
        score: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["score", b"score"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AssessResponse: _TypeAlias = AssessResponse  # noqa: Y015
