# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from prama_server.protos.sqa import ux_sqa_pb2 as prama__server_dot_protos_dot_sqa_dot_ux__sqa__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in prama_server/protos/sqa/ux_sqa_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UxSqaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Assess = channel.unary_unary(
                '/ux_sqa.UxSqa/Assess',
                request_serializer=prama__server_dot_protos_dot_sqa_dot_ux__sqa__pb2.AssessRequest.SerializeToString,
                response_deserializer=prama__server_dot_protos_dot_sqa_dot_ux__sqa__pb2.AssessResponse.FromString,
                _registered_method=True)


class UxSqaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Assess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UxSqaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Assess': grpc.unary_unary_rpc_method_handler(
                    servicer.Assess,
                    request_deserializer=prama__server_dot_protos_dot_sqa_dot_ux__sqa__pb2.AssessRequest.FromString,
                    response_serializer=prama__server_dot_protos_dot_sqa_dot_ux__sqa__pb2.AssessResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ux_sqa.UxSqa', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ux_sqa.UxSqa', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UxSqa(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Assess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ux_sqa.UxSqa/Assess',
            prama__server_dot_protos_dot_sqa_dot_ux__sqa__pb2.AssessRequest.SerializeToString,
            prama__server_dot_protos_dot_sqa_dot_ux__sqa__pb2.AssessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
