# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: prama_server/protos/sqa/ux_sqa.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'prama_server/protos/sqa/ux_sqa.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$prama_server/protos/sqa/ux_sqa.proto\x12\x06ux_sqa\"E\n\rAssessRequest\x12%\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x15.ux_sqa.QualityConfig\x12\r\n\x05\x61udio\x18\x02 \x01(\x0c\"\xa0\x01\n\rQualityConfig\x12\x35\n\x08\x65ncoding\x18\x01 \x01(\x0e\x32#.ux_sqa.QualityConfig.AudioEncoding\x12\x19\n\x11sample_rate_hertz\x18\x02 \x01(\r\"=\n\rAudioEncoding\x12\x1e\n\x1a\x41UDIO_ENCODING_UNSPECIFIED\x10\x00\x12\x0c\n\x08LINEAR16\x10\x01\"\x1f\n\x0e\x41ssessResponse\x12\r\n\x05score\x18\x01 \x01(\x02\x32\x42\n\x05UxSqa\x12\x39\n\x06\x41ssess\x12\x15.ux_sqa.AssessRequest\x1a\x16.ux_sqa.AssessResponse\"\x00\x42\x1a\n\ncom.ux.sqaB\nUxSqaProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'prama_server.protos.sqa.ux_sqa_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\ncom.ux.sqaB\nUxSqaProtoP\001'
  _globals['_ASSESSREQUEST']._serialized_start=48
  _globals['_ASSESSREQUEST']._serialized_end=117
  _globals['_QUALITYCONFIG']._serialized_start=120
  _globals['_QUALITYCONFIG']._serialized_end=280
  _globals['_QUALITYCONFIG_AUDIOENCODING']._serialized_start=219
  _globals['_QUALITYCONFIG_AUDIOENCODING']._serialized_end=280
  _globals['_ASSESSRESPONSE']._serialized_start=282
  _globals['_ASSESSRESPONSE']._serialized_end=313
  _globals['_UXSQA']._serialized_start=315
  _globals['_UXSQA']._serialized_end=381
# @@protoc_insertion_point(module_scope)
