export const completedSnapshot = {
  job_id: "job-manas-001",
  status: "completed",
  request: {
    task: "asr",
    target: "127.0.0.1:50011",
    dataset_path: "data-bin/audiofolder/asr-demo",
    split: "test",
    limit: null,
    language_code: "en-US",
    sample_rate: 16000,
    min_reference_words: 5,
    hotwords: [],
    hotword_bias: 0,
    connect_timeout_seconds: 10,
    request_timeout_seconds: 60,
    interim_results: true,
    inference_concurrency: 0,
    asr_inference_concurrency: 0,
    vad_inference_concurrency: 0,
    lid_inference_concurrency: 0,
    enable_mos: false,
    mos_target: "",
    enable_snr: false,
    snr_target: "",
    sqa_inference_concurrency: 0,
    lid_confidence_threshold: 0,
    remove_punctuation: false,
    mask_frame_seconds: 0.01,
    chunk_duration_seconds: 0.1,
    speech_padding_seconds: 0,
    hit_threshold: 0.9,
    streaming: false,
  },
  progress: { status: "completed", total: 1, processed: 1, evaluated: 1 },
  result: {
    wer: 0.25,
    cer: 0.12,
    word_accuracy: 0.75,
    character_accuracy: 0.88,
    sample_count: 1,
    wer_report: {
      summary: {
        wer: 0.25,
        hits: 3,
        substitutions: 1,
        deletions: 0,
        insertions: 0,
      },
      utterances: [
        {
          id: "sample-001",
          index: 1,
          summary: {
            wer: 0.25,
            hits: 3,
            substitutions: 1,
            deletions: 0,
            insertions: 0,
          },
          tokens: [
            { ref: "hello", hyp: "hello", label: "equal" },
            { ref: "world", hyp: "word", label: "substitution" },
          ],
        },
      ],
    },
    cer_report: {
      summary: {
        wer: 0.12,
        hits: 8,
        substitutions: 1,
        deletions: 0,
        insertions: 0,
      },
      utterances: [],
    },
  },
  error: null,
};

export const completedVadSnapshot = {
  ...completedSnapshot,
  job_id: "job-vad-001",
  request: {
    ...completedSnapshot.request,
    task: "vad",
    target: "192.168.0.222:50021",
    dataset_path: "data-bin/audiofolder/vad-demo",
    min_reference_words: 0,
  },
  progress: { status: "completed", total: 3, processed: 3, evaluated: 3 },
  result: {
    sample_count: 3,
    included_sample_count: 3,
    audio_duration_seconds: 30,
    processing_elapsed_seconds: 0.5,
    realtime_factor: 60,
    frame: { frame_f1: 0.9 },
    segment: {
      reference_segment_count: 3,
      prediction_segment_count: 4,
      segment_miss_count: 1,
      segment_false_alarm_count: 1,
      segment_recall: 2 / 3,
      segment_precision: 3 / 4,
      segment_f1: 0.7059,
    },
    vad_report: {
      samples: [
        {
          id: "sample-miss",
          index: 1,
          duration_seconds: 10,
          frame_seconds: 0.01,
          metrics: {
            frame: { frame_f1: 0.8 },
            segment: { segment_miss_count: 1, segment_false_alarm_count: 0 },
          },
          reference_segments: [
            {
              start: 1,
              end: 4,
              duration: 3,
              start_frame: 100,
              end_frame: 400,
              status: "miss",
            },
          ],
          prediction_segments: [
            {
              start: 1,
              end: 2,
              duration: 1,
              start_frame: 100,
              end_frame: 200,
              status: "hit",
            },
          ],
          regions: [
            {
              start: 2,
              end: 4,
              duration: 2,
              start_frame: 200,
              end_frame: 400,
              label: "miss",
            },
          ],
        },
        {
          id: "sample-split",
          index: 2,
          duration_seconds: 10,
          frame_seconds: 0.01,
          metrics: {
            frame: { frame_f1: 0.86 },
            segment: { segment_miss_count: 0, segment_false_alarm_count: 1 },
          },
          reference_segments: [
            {
              start: 2,
              end: 7,
              duration: 5,
              start_frame: 200,
              end_frame: 700,
              status: "hit",
            },
          ],
          prediction_segments: [
            {
              start: 2,
              end: 4,
              duration: 2,
              start_frame: 200,
              end_frame: 400,
              status: "hit",
            },
            {
              start: 4.2,
              end: 7,
              duration: 2.8,
              start_frame: 420,
              end_frame: 700,
              status: "hit",
            },
            {
              start: 8,
              end: 9,
              duration: 1,
              start_frame: 800,
              end_frame: 900,
              status: "false_alarm",
            },
          ],
          regions: [
            {
              start: 8,
              end: 9,
              duration: 1,
              start_frame: 800,
              end_frame: 900,
              label: "false_alarm",
            },
          ],
        },
        {
          id: "sample-good",
          index: 3,
          duration_seconds: 10,
          frame_seconds: 0.01,
          metrics: {
            frame: { frame_f1: 0.99 },
            segment: { segment_miss_count: 0, segment_false_alarm_count: 0 },
          },
          reference_segments: [
            {
              start: 3,
              end: 6,
              duration: 3,
              start_frame: 300,
              end_frame: 600,
              status: "hit",
            },
          ],
          prediction_segments: [
            {
              start: 3,
              end: 6,
              duration: 3,
              start_frame: 300,
              end_frame: 600,
              status: "hit",
            },
          ],
          regions: [
            {
              start: 3,
              end: 6,
              duration: 3,
              start_frame: 300,
              end_frame: 600,
              label: "hit",
            },
          ],
        },
      ],
    },
  },
};
