services:
  backend:
    image: registry.cn-hangzhou.aliyuncs.com/migo-dl/prama-server-backend:0.3.0a1
    container_name: prama-server-backend
    environment:
      PRAMA_WORKDIR: ${PRAMA_WORKDIR:-/data-bin}
    volumes:
      - ${PWD}/data-bin:/data-bin

  frontend:
    image: registry.cn-hangzhou.aliyuncs.com/migo-dl/prama-server-frontend:0.3.0a1
    container_name: prama-server-frontend
    environment:
      API_UPSTREAM: http://backend:8000
      CLIENT_MAX_BODY_SIZE: 10G
    depends_on:
      - backend
    ports:
      - "8080:80"
