"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import duration_pb2 as _duration_pb2
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class DetectRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONFIG_FIELD_NUMBER: _builtins.int
    AUDIO_FIELD_NUMBER: _builtins.int
    audio: _builtins.bytes
    @_builtins.property
    def config(self) -> Global___DetectionConfig: ...
    def __init__(
        self,
        *,
        config: Global___DetectionConfig | None = ...,
        audio: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["config", b"config"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["audio", b"audio", "config", b"config"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DetectRequest: _TypeAlias = DetectRequest  # noqa: Y015

@_typing.final
class DetectionConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _AudioEncoding:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _AudioEncodingEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[DetectionConfig._AudioEncoding.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        ENCODING_UNSPECIFIED: DetectionConfig._AudioEncoding.ValueType  # 0
        """Not specified."""
        LINEAR16: DetectionConfig._AudioEncoding.ValueType  # 1
        """16位有符号pcm (little-endian)"""

    class AudioEncoding(_AudioEncoding, metaclass=_AudioEncodingEnumTypeWrapper): ...
    ENCODING_UNSPECIFIED: DetectionConfig.AudioEncoding.ValueType  # 0
    """Not specified."""
    LINEAR16: DetectionConfig.AudioEncoding.ValueType  # 1
    """16位有符号pcm (little-endian)"""

    ENCODING_FIELD_NUMBER: _builtins.int
    SAMPLE_RATE_HERTZ_FIELD_NUMBER: _builtins.int
    encoding: Global___DetectionConfig.AudioEncoding.ValueType
    """音频编码"""
    sample_rate_hertz: _builtins.int
    """采样率"""
    def __init__(
        self,
        *,
        encoding: Global___DetectionConfig.AudioEncoding.ValueType = ...,
        sample_rate_hertz: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["encoding", b"encoding", "sample_rate_hertz", b"sample_rate_hertz"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DetectionConfig: _TypeAlias = DetectionConfig  # noqa: Y015

@_typing.final
class DetectResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RESULTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def results(self) -> _containers.RepeatedCompositeFieldContainer[Global___DetectionResult]: ...
    def __init__(
        self,
        *,
        results: _abc.Iterable[Global___DetectionResult] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["results", b"results"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DetectResponse: _TypeAlias = DetectResponse  # noqa: Y015

@_typing.final
class DetectionResult(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    START_TIME_FIELD_NUMBER: _builtins.int
    END_TIME_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def start_time(self) -> _duration_pb2.Duration: ...
    @_builtins.property
    def end_time(self) -> _duration_pb2.Duration: ...
    def __init__(
        self,
        *,
        start_time: _duration_pb2.Duration | None = ...,
        end_time: _duration_pb2.Duration | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["end_time", b"end_time", "start_time", b"start_time"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["end_time", b"end_time", "start_time", b"start_time"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DetectionResult: _TypeAlias = DetectionResult  # noqa: Y015

@_typing.final
class StreamingDetectRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONFIG_FIELD_NUMBER: _builtins.int
    AUDIO_CONTENT_FIELD_NUMBER: _builtins.int
    audio_content: _builtins.bytes
    @_builtins.property
    def config(self) -> Global___DetectionConfig: ...
    def __init__(
        self,
        *,
        config: Global___DetectionConfig | None = ...,
        audio_content: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["audio_content", b"audio_content", "config", b"config", "streaming_request", b"streaming_request"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["audio_content", b"audio_content", "config", b"config", "streaming_request", b"streaming_request"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_streaming_request: _TypeAlias = _typing.Literal["config", "audio_content"]  # noqa: Y015
    _WhichOneofArgType_streaming_request: _TypeAlias = _typing.Literal["streaming_request", b"streaming_request"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_streaming_request) -> _WhichOneofReturnType_streaming_request | None: ...

Global___StreamingDetectRequest: _TypeAlias = StreamingDetectRequest  # noqa: Y015

@_typing.final
class StreamingDetectResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RESULTS_FIELD_NUMBER: _builtins.int
    PROCESSED_TIME_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def results(self) -> _containers.RepeatedCompositeFieldContainer[Global___DetectionResult]: ...
    @_builtins.property
    def processed_time(self) -> _duration_pb2.Duration:
        """已处理的时长"""

    def __init__(
        self,
        *,
        results: _abc.Iterable[Global___DetectionResult] | None = ...,
        processed_time: _duration_pb2.Duration | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["processed_time", b"processed_time"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["processed_time", b"processed_time", "results", b"results"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StreamingDetectResponse: _TypeAlias = StreamingDetectResponse  # noqa: Y015
