# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from prama_server.protos.vad import ux_vad_pb2 as prama__server_dot_protos_dot_vad_dot_ux__vad__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in prama_server/protos/vad/ux_vad_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UxVoiceActivityDetectorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Detect = channel.unary_unary(
                '/ux_vad.UxVoiceActivityDetector/Detect',
                request_serializer=prama__server_dot_protos_dot_vad_dot_ux__vad__pb2.DetectRequest.SerializeToString,
                response_deserializer=prama__server_dot_protos_dot_vad_dot_ux__vad__pb2.DetectResponse.FromString,
                _registered_method=True)
        self.StreamingDetect = channel.stream_stream(
                '/ux_vad.UxVoiceActivityDetector/StreamingDetect',
                request_serializer=prama__server_dot_protos_dot_vad_dot_ux__vad__pb2.StreamingDetectRequest.SerializeToString,
                response_deserializer=prama__server_dot_protos_dot_vad_dot_ux__vad__pb2.StreamingDetectResponse.FromString,
                _registered_method=True)


class UxVoiceActivityDetectorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Detect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamingDetect(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UxVoiceActivityDetectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Detect': grpc.unary_unary_rpc_method_handler(
                    servicer.Detect,
                    request_deserializer=prama__server_dot_protos_dot_vad_dot_ux__vad__pb2.DetectRequest.FromString,
                    response_serializer=prama__server_dot_protos_dot_vad_dot_ux__vad__pb2.DetectResponse.SerializeToString,
            ),
            'StreamingDetect': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamingDetect,
                    request_deserializer=prama__server_dot_protos_dot_vad_dot_ux__vad__pb2.StreamingDetectRequest.FromString,
                    response_serializer=prama__server_dot_protos_dot_vad_dot_ux__vad__pb2.StreamingDetectResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ux_vad.UxVoiceActivityDetector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ux_vad.UxVoiceActivityDetector', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UxVoiceActivityDetector(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Detect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ux_vad.UxVoiceActivityDetector/Detect',
            prama__server_dot_protos_dot_vad_dot_ux__vad__pb2.DetectRequest.SerializeToString,
            prama__server_dot_protos_dot_vad_dot_ux__vad__pb2.DetectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamingDetect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ux_vad.UxVoiceActivityDetector/StreamingDetect',
            prama__server_dot_protos_dot_vad_dot_ux__vad__pb2.StreamingDetectRequest.SerializeToString,
            prama__server_dot_protos_dot_vad_dot_ux__vad__pb2.StreamingDetectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
