# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: prama_server/protos/vad/ux_vad.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'prama_server/protos/vad/ux_vad.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$prama_server/protos/vad/ux_vad.proto\x12\x06ux_vad\x1a\x1egoogle/protobuf/duration.proto\"G\n\rDetectRequest\x12\'\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x17.ux_vad.DetectionConfig\x12\r\n\x05\x61udio\x18\x02 \x01(\x0c\"\x9e\x01\n\x0f\x44\x65tectionConfig\x12\x37\n\x08\x65ncoding\x18\x01 \x01(\x0e\x32%.ux_vad.DetectionConfig.AudioEncoding\x12\x19\n\x11sample_rate_hertz\x18\x02 \x01(\r\"7\n\rAudioEncoding\x12\x18\n\x14\x45NCODING_UNSPECIFIED\x10\x00\x12\x0c\n\x08LINEAR16\x10\x01\":\n\x0e\x44\x65tectResponse\x12(\n\x07results\x18\x01 \x03(\x0b\x32\x17.ux_vad.DetectionResult\"m\n\x0f\x44\x65tectionResult\x12-\n\nstart_time\x18\x02 \x01(\x0b\x32\x19.google.protobuf.Duration\x12+\n\x08\x65nd_time\x18\x03 \x01(\x0b\x32\x19.google.protobuf.Duration\"q\n\x16StreamingDetectRequest\x12)\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x17.ux_vad.DetectionConfigH\x00\x12\x17\n\raudio_content\x18\x02 \x01(\x0cH\x00\x42\x13\n\x11streaming_request\"v\n\x17StreamingDetectResponse\x12(\n\x07results\x18\x01 \x03(\x0b\x32\x17.ux_vad.DetectionResult\x12\x31\n\x0eprocessed_time\x18\x02 \x01(\x0b\x32\x19.google.protobuf.Duration2\xae\x01\n\x17UxVoiceActivityDetector\x12\x39\n\x06\x44\x65tect\x12\x15.ux_vad.DetectRequest\x1a\x16.ux_vad.DetectResponse\"\x00\x12X\n\x0fStreamingDetect\x12\x1e.ux_vad.StreamingDetectRequest\x1a\x1f.ux_vad.StreamingDetectResponse\"\x00(\x01\x30\x01\x42-\n\ncom.ux.vadB\nUxVadProtoP\x01Z\x11ulang.com/vad;vadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'prama_server.protos.vad.ux_vad_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\ncom.ux.vadB\nUxVadProtoP\001Z\021ulang.com/vad;vad'
  _globals['_DETECTREQUEST']._serialized_start=80
  _globals['_DETECTREQUEST']._serialized_end=151
  _globals['_DETECTIONCONFIG']._serialized_start=154
  _globals['_DETECTIONCONFIG']._serialized_end=312
  _globals['_DETECTIONCONFIG_AUDIOENCODING']._serialized_start=257
  _globals['_DETECTIONCONFIG_AUDIOENCODING']._serialized_end=312
  _globals['_DETECTRESPONSE']._serialized_start=314
  _globals['_DETECTRESPONSE']._serialized_end=372
  _globals['_DETECTIONRESULT']._serialized_start=374
  _globals['_DETECTIONRESULT']._serialized_end=483
  _globals['_STREAMINGDETECTREQUEST']._serialized_start=485
  _globals['_STREAMINGDETECTREQUEST']._serialized_end=598
  _globals['_STREAMINGDETECTRESPONSE']._serialized_start=600
  _globals['_STREAMINGDETECTRESPONSE']._serialized_end=718
  _globals['_UXVOICEACTIVITYDETECTOR']._serialized_start=721
  _globals['_UXVOICEACTIVITYDETECTOR']._serialized_end=895
# @@protoc_insertion_point(module_scope)
