"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
from prama_server.protos.vad import ux_vad_pb2 as _ux_vad_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class UxVoiceActivityDetectorStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> UxVoiceActivityDetectorAsyncStub: ...
    Detect: _grpc.UnaryUnaryMultiCallable[_ux_vad_pb2.DetectRequest, _ux_vad_pb2.DetectResponse]
    StreamingDetect: _grpc.StreamStreamMultiCallable[_ux_vad_pb2.StreamingDetectRequest, _ux_vad_pb2.StreamingDetectResponse]

@_typing.type_check_only
class UxVoiceActivityDetectorAsyncStub(UxVoiceActivityDetectorStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    Detect: _aio.UnaryUnaryMultiCallable[_ux_vad_pb2.DetectRequest, _ux_vad_pb2.DetectResponse]  # type: ignore[assignment]
    StreamingDetect: _aio.StreamStreamMultiCallable[_ux_vad_pb2.StreamingDetectRequest, _ux_vad_pb2.StreamingDetectResponse]  # type: ignore[assignment]

class UxVoiceActivityDetectorServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def Detect(
        self,
        request: _ux_vad_pb2.DetectRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_ux_vad_pb2.DetectResponse, _abc.Awaitable[_ux_vad_pb2.DetectResponse]]: ...

    @_abc_1.abstractmethod
    def StreamingDetect(
        self,
        request_iterator: _MaybeAsyncIterator[_ux_vad_pb2.StreamingDetectRequest],
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_ux_vad_pb2.StreamingDetectResponse], _abc.AsyncIterator[_ux_vad_pb2.StreamingDetectResponse]]: ...

def add_UxVoiceActivityDetectorServicer_to_server(servicer: UxVoiceActivityDetectorServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
