"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
from prama_server.protos.denoise import ux_denoise_pb2 as _ux_denoise_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class UxDenoiseStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> UxDenoiseAsyncStub: ...
    Denoise: _grpc.UnaryUnaryMultiCallable[_ux_denoise_pb2.DenoiseRequest, _ux_denoise_pb2.DenoiseResponse]
    StreamingDenoise: _grpc.StreamStreamMultiCallable[_ux_denoise_pb2.StreamingDenoiseRequest, _ux_denoise_pb2.StreamingDenoiseResponse]

@_typing.type_check_only
class UxDenoiseAsyncStub(UxDenoiseStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    Denoise: _aio.UnaryUnaryMultiCallable[_ux_denoise_pb2.DenoiseRequest, _ux_denoise_pb2.DenoiseResponse]  # type: ignore[assignment]
    StreamingDenoise: _aio.StreamStreamMultiCallable[_ux_denoise_pb2.StreamingDenoiseRequest, _ux_denoise_pb2.StreamingDenoiseResponse]  # type: ignore[assignment]

class UxDenoiseServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def Denoise(
        self,
        request: _ux_denoise_pb2.DenoiseRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_ux_denoise_pb2.DenoiseResponse, _abc.Awaitable[_ux_denoise_pb2.DenoiseResponse]]: ...

    @_abc_1.abstractmethod
    def StreamingDenoise(
        self,
        request_iterator: _MaybeAsyncIterator[_ux_denoise_pb2.StreamingDenoiseRequest],
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_ux_denoise_pb2.StreamingDenoiseResponse], _abc.AsyncIterator[_ux_denoise_pb2.StreamingDenoiseResponse]]: ...

def add_UxDenoiseServicer_to_server(servicer: UxDenoiseServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
