# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from prama_server.protos.denoise import ux_denoise_pb2 as prama__server_dot_protos_dot_denoise_dot_ux__denoise__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in prama_server/protos/denoise/ux_denoise_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UxDenoiseStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Denoise = channel.unary_unary(
                '/ux_denoise_proto.UxDenoise/Denoise',
                request_serializer=prama__server_dot_protos_dot_denoise_dot_ux__denoise__pb2.DenoiseRequest.SerializeToString,
                response_deserializer=prama__server_dot_protos_dot_denoise_dot_ux__denoise__pb2.DenoiseResponse.FromString,
                _registered_method=True)
        self.StreamingDenoise = channel.stream_stream(
                '/ux_denoise_proto.UxDenoise/StreamingDenoise',
                request_serializer=prama__server_dot_protos_dot_denoise_dot_ux__denoise__pb2.StreamingDenoiseRequest.SerializeToString,
                response_deserializer=prama__server_dot_protos_dot_denoise_dot_ux__denoise__pb2.StreamingDenoiseResponse.FromString,
                _registered_method=True)


class UxDenoiseServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Denoise(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamingDenoise(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UxDenoiseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Denoise': grpc.unary_unary_rpc_method_handler(
                    servicer.Denoise,
                    request_deserializer=prama__server_dot_protos_dot_denoise_dot_ux__denoise__pb2.DenoiseRequest.FromString,
                    response_serializer=prama__server_dot_protos_dot_denoise_dot_ux__denoise__pb2.DenoiseResponse.SerializeToString,
            ),
            'StreamingDenoise': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamingDenoise,
                    request_deserializer=prama__server_dot_protos_dot_denoise_dot_ux__denoise__pb2.StreamingDenoiseRequest.FromString,
                    response_serializer=prama__server_dot_protos_dot_denoise_dot_ux__denoise__pb2.StreamingDenoiseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ux_denoise_proto.UxDenoise', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ux_denoise_proto.UxDenoise', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UxDenoise(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Denoise(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ux_denoise_proto.UxDenoise/Denoise',
            prama__server_dot_protos_dot_denoise_dot_ux__denoise__pb2.DenoiseRequest.SerializeToString,
            prama__server_dot_protos_dot_denoise_dot_ux__denoise__pb2.DenoiseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamingDenoise(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ux_denoise_proto.UxDenoise/StreamingDenoise',
            prama__server_dot_protos_dot_denoise_dot_ux__denoise__pb2.StreamingDenoiseRequest.SerializeToString,
            prama__server_dot_protos_dot_denoise_dot_ux__denoise__pb2.StreamingDenoiseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
