# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: prama_server/protos/denoise/ux_denoise.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'prama_server/protos/denoise/ux_denoise.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,prama_server/protos/denoise/ux_denoise.proto\x12\x10ux_denoise_proto\"\x98\x01\n\x0e\x44\x65noiseRequest\x12\x38\n\x0f\x61udio_in_config\x18\x01 \x01(\x0b\x32\x1f.ux_denoise_proto.AudioInConfig\x12:\n\x10\x61udio_out_config\x18\x02 \x01(\x0b\x32 .ux_denoise_proto.AudioOutConfig\x12\x10\n\x08\x61udio_in\x18\x03 \x01(\x0c\"$\n\x0f\x44\x65noiseResponse\x12\x11\n\taudio_out\x18\x01 \x01(\x0c\"X\n\rAudioInConfig\x12,\n\x08\x65ncoding\x18\x01 \x01(\x0e\x32\x1a.ux_denoise_proto.Encoding\x12\x19\n\x11sample_rate_hertz\x18\x02 \x01(\r\"Y\n\x0e\x41udioOutConfig\x12,\n\x08\x65ncoding\x18\x01 \x01(\x0e\x32\x1a.ux_denoise_proto.Encoding\x12\x19\n\x11sample_rate_hertz\x18\x02 \x01(\r\"\x85\x01\n\rDenoiseConfig\x12\x38\n\x0f\x61udio_in_config\x18\x01 \x01(\x0b\x32\x1f.ux_denoise_proto.AudioInConfig\x12:\n\x10\x61udio_out_config\x18\x02 \x01(\x0b\x32 .ux_denoise_proto.AudioOutConfig\"h\n\x17StreamingDenoiseRequest\x12\x31\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x1f.ux_denoise_proto.DenoiseConfigH\x00\x12\x12\n\x08\x61udio_in\x18\x02 \x01(\x0cH\x00\x42\x06\n\x04type\"-\n\x18StreamingDenoiseResponse\x12\x11\n\taudio_out\x18\x01 \x01(\x0c*8\n\x08\x45ncoding\x12\x1e\n\x1a\x41UDIO_ENCODING_UNSPECIFIED\x10\x00\x12\x0c\n\x08LINEAR16\x10\x01\x32\xce\x01\n\tUxDenoise\x12P\n\x07\x44\x65noise\x12 .ux_denoise_proto.DenoiseRequest\x1a!.ux_denoise_proto.DenoiseResponse\"\x00\x12o\n\x10StreamingDenoise\x12).ux_denoise_proto.StreamingDenoiseRequest\x1a*.ux_denoise_proto.StreamingDenoiseResponse\"\x00(\x01\x30\x01\x42=\n\x0e\x63om.ux.denoiseB\x0eUxDenoiseProtoP\x01Z\x19ulang.com/denoise;denoiseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'prama_server.protos.denoise.ux_denoise_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016com.ux.denoiseB\016UxDenoiseProtoP\001Z\031ulang.com/denoise;denoise'
  _globals['_ENCODING']._serialized_start=729
  _globals['_ENCODING']._serialized_end=785
  _globals['_DENOISEREQUEST']._serialized_start=67
  _globals['_DENOISEREQUEST']._serialized_end=219
  _globals['_DENOISERESPONSE']._serialized_start=221
  _globals['_DENOISERESPONSE']._serialized_end=257
  _globals['_AUDIOINCONFIG']._serialized_start=259
  _globals['_AUDIOINCONFIG']._serialized_end=347
  _globals['_AUDIOOUTCONFIG']._serialized_start=349
  _globals['_AUDIOOUTCONFIG']._serialized_end=438
  _globals['_DENOISECONFIG']._serialized_start=441
  _globals['_DENOISECONFIG']._serialized_end=574
  _globals['_STREAMINGDENOISEREQUEST']._serialized_start=576
  _globals['_STREAMINGDENOISEREQUEST']._serialized_end=680
  _globals['_STREAMINGDENOISERESPONSE']._serialized_start=682
  _globals['_STREAMINGDENOISERESPONSE']._serialized_end=727
  _globals['_UXDENOISE']._serialized_start=788
  _globals['_UXDENOISE']._serialized_end=994
# @@protoc_insertion_point(module_scope)
