"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _Encoding:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _EncodingEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Encoding.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    AUDIO_ENCODING_UNSPECIFIED: _Encoding.ValueType  # 0
    LINEAR16: _Encoding.ValueType  # 1

class Encoding(_Encoding, metaclass=_EncodingEnumTypeWrapper): ...

AUDIO_ENCODING_UNSPECIFIED: Encoding.ValueType  # 0
LINEAR16: Encoding.ValueType  # 1
Global___Encoding: _TypeAlias = Encoding  # noqa: Y015

@_typing.final
class DenoiseRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    AUDIO_IN_CONFIG_FIELD_NUMBER: _builtins.int
    AUDIO_OUT_CONFIG_FIELD_NUMBER: _builtins.int
    AUDIO_IN_FIELD_NUMBER: _builtins.int
    audio_in: _builtins.bytes
    @_builtins.property
    def audio_in_config(self) -> Global___AudioInConfig: ...
    @_builtins.property
    def audio_out_config(self) -> Global___AudioOutConfig: ...
    def __init__(
        self,
        *,
        audio_in_config: Global___AudioInConfig | None = ...,
        audio_out_config: Global___AudioOutConfig | None = ...,
        audio_in: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["audio_in_config", b"audio_in_config", "audio_out_config", b"audio_out_config"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["audio_in", b"audio_in", "audio_in_config", b"audio_in_config", "audio_out_config", b"audio_out_config"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DenoiseRequest: _TypeAlias = DenoiseRequest  # noqa: Y015

@_typing.final
class DenoiseResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    AUDIO_OUT_FIELD_NUMBER: _builtins.int
    audio_out: _builtins.bytes
    def __init__(
        self,
        *,
        audio_out: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["audio_out", b"audio_out"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DenoiseResponse: _TypeAlias = DenoiseResponse  # noqa: Y015

@_typing.final
class AudioInConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ENCODING_FIELD_NUMBER: _builtins.int
    SAMPLE_RATE_HERTZ_FIELD_NUMBER: _builtins.int
    encoding: Global___Encoding.ValueType
    sample_rate_hertz: _builtins.int
    def __init__(
        self,
        *,
        encoding: Global___Encoding.ValueType = ...,
        sample_rate_hertz: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["encoding", b"encoding", "sample_rate_hertz", b"sample_rate_hertz"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AudioInConfig: _TypeAlias = AudioInConfig  # noqa: Y015

@_typing.final
class AudioOutConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ENCODING_FIELD_NUMBER: _builtins.int
    SAMPLE_RATE_HERTZ_FIELD_NUMBER: _builtins.int
    encoding: Global___Encoding.ValueType
    sample_rate_hertz: _builtins.int
    def __init__(
        self,
        *,
        encoding: Global___Encoding.ValueType = ...,
        sample_rate_hertz: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["encoding", b"encoding", "sample_rate_hertz", b"sample_rate_hertz"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AudioOutConfig: _TypeAlias = AudioOutConfig  # noqa: Y015

@_typing.final
class DenoiseConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    AUDIO_IN_CONFIG_FIELD_NUMBER: _builtins.int
    AUDIO_OUT_CONFIG_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def audio_in_config(self) -> Global___AudioInConfig: ...
    @_builtins.property
    def audio_out_config(self) -> Global___AudioOutConfig: ...
    def __init__(
        self,
        *,
        audio_in_config: Global___AudioInConfig | None = ...,
        audio_out_config: Global___AudioOutConfig | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["audio_in_config", b"audio_in_config", "audio_out_config", b"audio_out_config"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["audio_in_config", b"audio_in_config", "audio_out_config", b"audio_out_config"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DenoiseConfig: _TypeAlias = DenoiseConfig  # noqa: Y015

@_typing.final
class StreamingDenoiseRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONFIG_FIELD_NUMBER: _builtins.int
    AUDIO_IN_FIELD_NUMBER: _builtins.int
    audio_in: _builtins.bytes
    @_builtins.property
    def config(self) -> Global___DenoiseConfig: ...
    def __init__(
        self,
        *,
        config: Global___DenoiseConfig | None = ...,
        audio_in: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["audio_in", b"audio_in", "config", b"config", "type", b"type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["audio_in", b"audio_in", "config", b"config", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_type: _TypeAlias = _typing.Literal["config", "audio_in"]  # noqa: Y015
    _WhichOneofArgType_type: _TypeAlias = _typing.Literal["type", b"type"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_type) -> _WhichOneofReturnType_type | None: ...

Global___StreamingDenoiseRequest: _TypeAlias = StreamingDenoiseRequest  # noqa: Y015

@_typing.final
class StreamingDenoiseResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    AUDIO_OUT_FIELD_NUMBER: _builtins.int
    audio_out: _builtins.bytes
    def __init__(
        self,
        *,
        audio_out: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["audio_out", b"audio_out"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StreamingDenoiseResponse: _TypeAlias = StreamingDenoiseResponse  # noqa: Y015
