"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class MsgLidGetLanguagesReq(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MsgLidGetLanguagesReq: _TypeAlias = MsgLidGetLanguagesReq  # noqa: Y015

@_typing.final
class MsgLidGetLanguagesRes(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class DataEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.int
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.int = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    DATA_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def data(self) -> _containers.ScalarMap[_builtins.int, _builtins.str]: ...
    def __init__(
        self,
        *,
        data: _abc.Mapping[_builtins.int, _builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MsgLidGetLanguagesRes: _TypeAlias = MsgLidGetLanguagesRes  # noqa: Y015

@_typing.final
class MsgLidProcessReq(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PCM_FIELD_NUMBER: _builtins.int
    SAMPLERATE_FIELD_NUMBER: _builtins.int
    CHANNEL_FIELD_NUMBER: _builtins.int
    BITSPERSAMPLE_FIELD_NUMBER: _builtins.int
    pcm: _builtins.bytes
    """wav pcm"""
    sampleRate: _builtins.int
    """采样率"""
    channel: _builtins.int
    """声道数"""
    bitsPerSample: _builtins.int
    """样本位数"""
    def __init__(
        self,
        *,
        pcm: _builtins.bytes = ...,
        sampleRate: _builtins.int = ...,
        channel: _builtins.int = ...,
        bitsPerSample: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bitsPerSample", b"bitsPerSample", "channel", b"channel", "pcm", b"pcm", "sampleRate", b"sampleRate"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MsgLidProcessReq: _TypeAlias = MsgLidProcessReq  # noqa: Y015

@_typing.final
class MsgLidProcessRes(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LANG_FIELD_NUMBER: _builtins.int
    SCORE_FIELD_NUMBER: _builtins.int
    lang: _builtins.str
    """Lid 结果"""
    score: _builtins.float
    """Lid 得分"""
    def __init__(
        self,
        *,
        lang: _builtins.str = ...,
        score: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["lang", b"lang", "score", b"score"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MsgLidProcessRes: _TypeAlias = MsgLidProcessRes  # noqa: Y015
