# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: prama_server/protos/lid/lid.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'prama_server/protos/lid/lid.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!prama_server/protos/lid/lid.proto\x12\x03lid\"\x17\n\x15MsgLidGetLanguagesReq\"x\n\x15MsgLidGetLanguagesRes\x12\x32\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32$.lid.MsgLidGetLanguagesRes.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"[\n\x10MsgLidProcessReq\x12\x0b\n\x03pcm\x18\x01 \x01(\x0c\x12\x12\n\nsampleRate\x18\x02 \x01(\x05\x12\x0f\n\x07\x63hannel\x18\x03 \x01(\x05\x12\x15\n\rbitsPerSample\x18\x04 \x01(\x05\"/\n\x10MsgLidProcessRes\x12\x0c\n\x04lang\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x02\x32\x8d\x01\n\nLidService\x12\x37\n\x07Process\x12\x15.lid.MsgLidProcessReq\x1a\x15.lid.MsgLidProcessRes\x12\x46\n\x0cGetLanguages\x12\x1a.lid.MsgLidGetLanguagesReq\x1a\x1a.lid.MsgLidGetLanguagesResB\x1eZ\x1c\x31\x39\x32.168.0.241/d145/proto/lidb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'prama_server.protos.lid.lid_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\034192.168.0.241/d145/proto/lid'
  _globals['_MSGLIDGETLANGUAGESRES_DATAENTRY']._loaded_options = None
  _globals['_MSGLIDGETLANGUAGESRES_DATAENTRY']._serialized_options = b'8\001'
  _globals['_MSGLIDGETLANGUAGESREQ']._serialized_start=42
  _globals['_MSGLIDGETLANGUAGESREQ']._serialized_end=65
  _globals['_MSGLIDGETLANGUAGESRES']._serialized_start=67
  _globals['_MSGLIDGETLANGUAGESRES']._serialized_end=187
  _globals['_MSGLIDGETLANGUAGESRES_DATAENTRY']._serialized_start=144
  _globals['_MSGLIDGETLANGUAGESRES_DATAENTRY']._serialized_end=187
  _globals['_MSGLIDPROCESSREQ']._serialized_start=189
  _globals['_MSGLIDPROCESSREQ']._serialized_end=280
  _globals['_MSGLIDPROCESSRES']._serialized_start=282
  _globals['_MSGLIDPROCESSRES']._serialized_end=329
  _globals['_LIDSERVICE']._serialized_start=332
  _globals['_LIDSERVICE']._serialized_end=473
# @@protoc_insertion_point(module_scope)
