"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
from prama_server.protos.lid import lid_pb2 as _lid_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class LidServiceStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> LidServiceAsyncStub: ...
    Process: _grpc.UnaryUnaryMultiCallable[_lid_pb2.MsgLidProcessReq, _lid_pb2.MsgLidProcessRes]
    GetLanguages: _grpc.UnaryUnaryMultiCallable[_lid_pb2.MsgLidGetLanguagesReq, _lid_pb2.MsgLidGetLanguagesRes]

@_typing.type_check_only
class LidServiceAsyncStub(LidServiceStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    Process: _aio.UnaryUnaryMultiCallable[_lid_pb2.MsgLidProcessReq, _lid_pb2.MsgLidProcessRes]  # type: ignore[assignment]
    GetLanguages: _aio.UnaryUnaryMultiCallable[_lid_pb2.MsgLidGetLanguagesReq, _lid_pb2.MsgLidGetLanguagesRes]  # type: ignore[assignment]

class LidServiceServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def Process(
        self,
        request: _lid_pb2.MsgLidProcessReq,
        context: _ServicerContext,
    ) -> _typing.Union[_lid_pb2.MsgLidProcessRes, _abc.Awaitable[_lid_pb2.MsgLidProcessRes]]: ...

    @_abc_1.abstractmethod
    def GetLanguages(
        self,
        request: _lid_pb2.MsgLidGetLanguagesReq,
        context: _ServicerContext,
    ) -> _typing.Union[_lid_pb2.MsgLidGetLanguagesRes, _abc.Awaitable[_lid_pb2.MsgLidGetLanguagesRes]]: ...

def add_LidServiceServicer_to_server(servicer: LidServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
